name: Build and Publish Caddy with L4

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      caddy_version:
        description: 'Caddy version (e.g., 2.10.2)'
        required: true
        default: '2'
        type: string
  workflow_call:
    inputs:
      caddy_version:
        description: 'Caddy version to use in the build'
        required: true
        type: string

# Define permissions needed for this workflow
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Don't run on PRs by default
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Resolve Caddy version
        id: caddy_version
        shell: bash
        run: |
          set -euo pipefail

          VERSION="${{ inputs.caddy_version }}"
          if [ -z "$VERSION" ]; then
            VERSION="${{ github.event.inputs.caddy_version }}"
          fi
          if [ -z "$VERSION" ]; then
            VERSION="2"
          fi

          VERSION=${VERSION//-alpine/}
          VERSION=${VERSION//-builder/}

          echo "Resolved Caddy version: $VERSION"
          echo "CADDY_VERSION=$VERSION" >> "$GITHUB_ENV"
          echo "value=$VERSION" >> "$GITHUB_OUTPUT"

      - name: Log in to the Container registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}
            type=raw,value=${{ steps.caddy_version.outputs.value }},enable=${{ github.event_name == 'workflow_dispatch' || github.event_name == 'workflow_call' }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            CADDY_VERSION=${{ env.CADDY_VERSION }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
