name: Test Docker Build

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'Dockerfile'
      - '.github/workflows/docker-build-publish.yml'

# Define permissions needed for this workflow
permissions:
  contents: read

jobs:
  test-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        caddy-version: ['2', '2.7.4']
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: false
          tags: caddy-with-l4:${{ matrix.caddy-version }}
          build-args: |
            CADDY_VERSION=${{ matrix.caddy-version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Test the image
        run: |
          docker run --rm caddy-with-l4:${{ matrix.caddy-version }} caddy version
          # Check if L4 module is included
          docker run --rm caddy-with-l4:${{ matrix.caddy-version }} caddy list-modules | grep l4
